version: "3.9"
services:
  webapp:
    image: nginx
    volumes:
     - /tmp/templates:/etc/nginx/templates
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    restart: always
  kiosk:
    build: ./kiosk
    image: kiosk
    privileged: yes
    command: "http://webapp/"
    restart: always
